### ISSUE TITLE
README Corrections

### ISSUE THREAD

**Issue by Crysmiss** [FancyPixel/moby#1]
Hi there, just three corrections to make in README.md! 

Line 8: 'CoreHaptics` → `Core Haptics`
Line 8: avaialble→ available
Line 9: [Catain AHAP] → [Captain AHAP]
Line 17: fel the haptics → feel the haptics
[README.md.zip](https://github.com/FancyPixel/moby/files/3340256/README.md.zip)

**Comment by andreamazz** [comment]
Thanks ✌️
