### ISSUE TITLE
No sync when editing intensity or sharpness of an event

### ISSUE THREAD

**Issue by persello** [FancyPixel/moby#7]
Add an event and try to edit its intensity or its sharpness in the online editor, then click on "Load ahap" on the Moby app. The vibration profile is not updated until another event is added or removed (and this can also be seen on the bottom right near the "Share options" button), but the "code" section of the online editor is automatically updated.

**Comment by andreamazz** [comment]
Hey @persello 
Nice catch, I've updated the frontend, feel free to refresh and try again, now all changes should be tracked.
