### ISSUE TITLE
Captain AHAP vs HTTPS

### ISSUE THREAD

**Issue by justingeeslin** [FancyPixel/moby#8]
Browsers disallow requests of HTTP when the originating page was loaded via HTTPS. This keeps a user from "Save and Share"ing the result of the editor, Captain AHAP.  See screenshot. 

Is Captain AHAP open source? If so, I can likely submit a PR to fix. 

<img width="1274" alt="Screen Shot 2020-11-18 at 4 46 53 PM" src="https://user-images.githubusercontent.com/1075425/99599183-6fbc4080-29c0-11eb-9fb9-c34ced707feb.png">

**Comment by andreamazz** [comment]
Hey @justingeeslin 
Thanks for the heads up, I forgot to update the endpoint when we enabled the forced https. I't now fixed 👍
