### ISSUE TITLE
version control / Paste code into editor?

### ISSUE THREAD

**Issue by guiseiz** [FancyPixel/moby#9]
any chance you might be allowing code pasting into editor?

getting change requests only for the changes to eventually be reverted - and when that happens have to painstakingly re-add all the things i deleted. 

wondering if there's a really cheap way of version controlling.

ie - copy current version to my code editor. If i want to revert changes i just paste the json code back to Captain Ahap?

that would be such a lifesaver 🙏

**Comment by andreamazz** [comment]
Hi @guiseiz 
Sorry for the delay. I've added a "Load from JSON" button in the UI, just paste over an AHAP file there to load it in the editor. 

Hope this helps 👍
